# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_speech_id', models.IntegerField()),
                ('order_stu_number', models.IntegerField()),
                ('order_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_id', models.IntegerField()),
                ('speech_name', models.TextField()),
                ('speech_speaker', models.TextField()),
                ('speech_introduction', models.TextField()),
                ('speech_time', models.TextField()),
                ('speech_place', models.TextField()),
                ('speech_capacity', models.IntegerField()),
                ('speech_chair_remain_numebr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_number', models.IntegerField()),
                ('stu_name', models.TextField()),
                ('stu_college', models.TextField()),
                ('stu_class', models.TextField()),
                ('stu_phone_number', models.TextField()),
            ],
        ),
    ]
