# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech',
            old_name='speech_speaker',
            new_name='speech_speaker_name',
        ),
        migrations.AddField(
            model_name='speech',
            name='speech_speaker_introduction',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
