# Generated by Django 2.1.1 on 2018-09-11 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0003_auto_20180910_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='speech_add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingorder',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
