# Generated by Django 2.1.1 on 2018-09-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0004_auto_20180911_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingOrder',
        ),
        migrations.DeleteModel(
            name='Speech',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
