# Generated by Django 2.1.1 on 2018-09-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookingApp', '0005_auto_20180911_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_speech_id', models.IntegerField()),
                ('order_stu_number', models.IntegerField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_stu_phone_number', models.TextField()),
                ('order_stu_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_name', models.TextField()),
                ('speech_speaker_name', models.TextField()),
                ('speech_speaker_introduction', models.TextField()),
                ('speech_introduction', models.TextField()),
                ('speech_time', models.TextField()),
                ('speech_place', models.TextField()),
                ('speech_capacity', models.IntegerField()),
                ('speech_chair_remain_number', models.IntegerField()),
                ('speech_add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_number', models.TextField()),
                ('stu_name', models.TextField()),
                ('stu_college', models.TextField()),
                ('stu_class', models.TextField()),
                ('stu_phone_number', models.TextField()),
            ],
        ),
    ]
