# Generated by Django 2.1.1 on 2018-09-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0006_bookingorder_speech_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorder',
            name='order_stu_number',
            field=models.TextField(),
        ),
    ]
