# Generated by Django 2.0.5 on 2018-09-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0007_auto_20180911_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingorder',
            options={'ordering': ['-order_time'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['-speech_add_time'], 'verbose_name': '讲座', 'verbose_name_plural': '讲座'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['stu_number'], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
    ]
